### PR TITLE
Support multiple host connections

### PR DESCRIPTION
**Pull request by Lujeni**
## extend commit 
- PEP8 compliance
- use round robin + context manager
- add unittests

### CODE REVIEW

**Comment by btall** [comment]
very interesting :) :+1:

**Comment by ultrabug** [comment]
:+1: thx

**Comment by ultrabug** [comment]
@lsjostro FYI reviewed and tested OK here, works like a charm and is backward compatible

**Comment by lsjostro** [comment]
This is awesome work! Thanks a lot guys! :)

**Comment by lsjostro** [comment]
I will have a look at in and probably merge it later today..

**Comment by ultrabug** [comment]
Cheers @lsjostro, once merged I guess we're good to go for a tag / release :) :ok_hand:

**Comment by lsjostro** [comment]
Thanks guys for the work! Merged and released to pypi!

**Comment by ramnes** [comment]
:balloon: :dancer: :tada:

**Pull request merged**
