### PR TITLE
add support for batch append operations

### PR DESCRIPTION
**Pull request by ultrabug**
...when passing a list to the logger !

quick benchmark : 
````
    10000 msg in 37.5808801651 s = 266.0 msg/s
    10000 bulked msg in 1.53806114197 s = 6501.0 msg/s
````

@lsjostro I'm disappointed by the poor throughput on a msg/msg basis. Do you have some insight or tips about ways to get a better performance ?

PS: I see that `# Autogenerated by Thrift Compiler (0.9.0)` on the ThriftSourceProtocol.py file, would you care to update it with the newer Thrift 0.9.3 maybe ?

### CODE REVIEW

**Comment by lsjostro** [comment]
Morning @ultrabug! Nice stats! The PR looks fine! Thanks! The poor perf on msg/msg is interesting.. I think it definitely the thrift implementation.. It would be great if we could bump the Thrift version and try to autogen a new thrift interfaces. I might have some time later this week..  If you have some spare time to do it that would be even more awesome! ;)  

Cheers,
Lars

**Comment by ultrabug** [comment]
Morning @lsjostro.

Well I must admit that I have no idea how you generated this file so if you think you can explain it quicker than actually doing it, I'll be glad to try ;) cheers.

**Comment by lsjostro** [comment]
No worries it's a bit cumbersome. ;)

Install thrift:
https://thrift.apache.org

Download this thrift files from flume (observe that the flumeCompatibility.thrift is Flume-og): 
https://github.com/apache/flume/search?l=thrift&q=thrift&utf8=%E2%9C%93

Run:
thrift --gen python <thrift-file>

**Comment by Lujeni** [comment]
@lsjostro @ultrabug 
BTW with the `thrift 9.3` version the generator is `py` not `python`.

**Pull request merged**
