### PR TITLE
Python 2.6/3.0 compatibility

### PR DESCRIPTION
**Pull request by ecesena**

### CODE REVIEW

**Comment by lsjostro** [comment]
LGTM :+1:  Thanks a lot!

**Comment by ultrabug** [comment]
@lsjostro you just overwrote #13 with this merge. It seems @ecesena didn't rebase properly before the PR ?

**Comment by ultrabug** [comment]
Actually it's not even a rebase sorry, but a rewrite with a useless condition... care to explain a bit more @ecesena ? Sorry if it's obvious to you and if my question is stupid...

**Comment by lsjostro** [comment]
opss my bad.. I'll do revert.

**Comment by lsjostro** [comment]
@ultrabug pointed out make since. Please elaborate.

**Comment by lsjostro** [comment]
I reverted the merge for now. Please open a new PR.

**Comment by ecesena** [comment]
Sorry guys, I was traveling - https://github.com/lsjostro/flumelogger/pull/13 wasn't into master, I didn't notice it.

I don't think it's a good idea to have an empty dict as default param, as that's mutable and won't behave as you expect (unless you did it on purpose). See, e.g., https://pythonconquerstheuniverse.wordpress.com/category/python-gotchas/

Please LMK if you'd like the full patch (I still recommend it), or just the fix to the format strings.

**Comment by ultrabug** [comment]
@ecesena well **thank you** I just learnt two things :
- I'm a newbie pythonista
- I didn't fully understand mutable default parameters

I'm thus gladly standing corrected and vouch for your solution :)

**Comment by lsjostro** [comment]
@ecesena @ultrabug thanks a lot guys!
New version has been tagged. Will release it to pypi when I get home tonight.

**Comment by ecesena** [comment]
No problem, happy that you learned something new :)

@lsjostro I think something messy happened with these merges & reverts. The master (and tag 0.4.2) doesn't contain this PR.

**Comment by lsjostro** [comment]
indeed I did.. now fixed. sorry for that.
to much stuff on my plate currently..

**Comment by ecesena** [comment]
Not a problem - that's the nice of open source, more eyes... :)

**Pull request merged**
