### PR TITLE
Regenerated thrift flume using thrift 0.9.3

### PR DESCRIPTION
**Pull request by lsjostro**
@ultrabug would you mind testing this out before we merge? I do not have flume available at the moment.

### CODE REVIEW

**Comment by ultrabug** [comment]
@lsjostro thanks, tested all OK to me, performances are better but not insane...

````
10000 msg in 32.3187279701 s = 309.0 msg/s
10000 bulked msg in 1.59791994095 s = 6258.0 msg/s
````

**Comment by lsjostro** [comment]
@ultrabug cool! Thanks! Will go a head and merge this then..
I will bump the version in a another commit and push to pypi..

**Comment by ultrabug** [comment]
@lsjostro if you can still wait a bit for the new release tag, would be great :)

**Comment by lsjostro** [comment]
Sure I'll wait with the push to pypi then...

**Pull request merged**
